import { mediaUrl } from '../config/media'
import type { PhotoMemory } from './types'

const photos: PhotoMemory[] = [
  {
    id: 'adventure-001',
    thumbSrc: mediaUrl('photos/adventures/block-01/adventure-001-480.webp'),
    displaySrc: mediaUrl('photos/adventures/block-01/adventure-001-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBACdASoWAB4APvVmrlEqpSQisBgIAVAeiUAVHoHl6oGV07opeGvORzhlUgAA/tAsoWcILxYALHy+2konp3jmggY1sXK8Fryd6aUGYVafep+DFIx/hD/1O33oZWVgRPfc1Keo7EFdcNwMEW11jG01vVRQS2H2GoZUMoDzdAAAAA==',
    width: 960,
    height: 1280,
    alt: 'Andre and Emily — Before we even left the house',
    caption: 'Before we even left the house',
    orientation: 'portrait',
    position: '50% 42%',
    chapter: 'adventures',
  },
  {
    id: 'adventure-002',
    thumbSrc: mediaUrl('photos/adventures/block-01/adventure-002-480.webp'),
    displaySrc: mediaUrl('photos/adventures/block-01/adventure-002-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoeAA4ALrl6vV6jqqqqioC4SxgE6AIdyGMOD+MqgNAsY1GwAOIGKfcJodh3hC9aPNedAyJdMSvBVoA16/lOiphbbdWs4UBFdkt3QugNeQ0k4SJI1juzwAAA',
    width: 1280,
    height: 592,
    alt: 'Andre and Emily — Coffee, a kiss and another ordinary-perfect day',
    caption: 'Coffee, a kiss and another ordinary-perfect day',
    orientation: 'landscape',
    position: '50% 45%',
    chapter: 'adventures',
  },
  {
    id: 'adventure-003',
    thumbSrc: mediaUrl('photos/adventures/block-01/adventure-003-480.webp'),
    displaySrc: mediaUrl('photos/adventures/block-01/adventure-003-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwBACdASoeAA4APvVork8qpiSiMAgBUB6JQBdmUABYNvX2AIg7iORKOgJYAAD+47tQg5GCI1agMnTca02HTQVXPJrnL0djqOS99MkbBzSsjA/ujsn96LA1s3nY5O+xwAGAAA==',
    width: 1280,
    height: 592,
    alt: 'Andre and Emily — The kind of smile that makes the whole day better',
    caption: 'The kind of smile that makes the whole day better',
    orientation: 'landscape',
    position: '50% 45%',
    chapter: 'adventures',
  },
  {
    id: 'adventure-004',
    thumbSrc: mediaUrl('photos/adventures/block-01/adventure-004-480.webp'),
    displaySrc: mediaUrl('photos/adventures/block-01/adventure-004-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoeAA4APvVmqk4qpaQiMAgBUB6JZgCdMoAKReslkGP93Idc+gAA/vQISuLc7O/geO8PZO3ADcE4wVmuPWmEddgrNmqzS/WLLCeGilFwGt4XhFUFWjCnFAAA',
    width: 1280,
    height: 592,
    alt: 'Andre and Emily — Sunshine, sea views and one more kiss',
    caption: 'Sunshine, sea views and one more kiss',
    orientation: 'landscape',
    position: '50% 45%',
    chapter: 'adventures',
  },
  {
    id: 'adventure-005',
    thumbSrc: mediaUrl('photos/adventures/block-01/adventure-005-480.webp'),
    displaySrc: mediaUrl('photos/adventures/block-01/adventure-005-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoeAA4APvVmqk4qpaQiMAgBUB6JZACdMoACjjNCgPzC1gHeLAAA/RNj5oWksv0q+ELzOpE5+03JbPW51FwNRfaRHH1ED6feLquJeAHRcXmkmEp4azOHlRwA',
    width: 1280,
    height: 592,
    alt: 'Andre and Emily — A day out with two unexpected witnesses',
    caption: 'A day out with two unexpected witnesses',
    orientation: 'landscape',
    position: '50% 48%',
    chapter: 'adventures',
  },
]

export default photos
