import { mediaUrl } from '../config/media'
import type { PhotoMemory } from './types'

const photos: PhotoMemory[] = [
  {
    id: 'alicante-001',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-001-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-001-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACwAwCdASoYAAsAPwFsrk+rJiQiMAgBYCAJZgCdAAtZGm2LOSnoAAD+oSOS1XlDaQTRMRz7UtttyEPgFAt2z0eCTDvCW3Kue1eMcEShQ3itANUIy1cbrgQyQ98FZ+4llTS5o9XYvIpFVbS7/ymqPmwd62U+pt31nvl/pX1BAAA=',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — Palm trees, sunshine and the two of us',
    caption: 'Palm trees, sunshine and the two of us',
    orientation: 'landscape',
    position: '50% 48%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-002',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-002-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-002-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoYAAsAPwFqrU8rJiQiMAgBYCAJQBOgBCOtSvHrXU2PNbgAAPfeg4oFXNbs46tR41qitbzFaKDBWlcKpeYZwIioQ1u/FOrTnFaG1MZsG5kDs1x0QMbpC3CQc8qQ+RMEVmHHrfLWc5emZ/npAhYRxkCUNpFzEUAA',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — Emily, casually making friends with a camel',
    caption: 'Emily, casually making friends with a camel',
    orientation: 'landscape',
    position: '50% 48%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-003',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-003-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-003-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBACdASoYAAsAPwFqrE6rJiQiMAgBYCAJZACdMoACPAhDgDe7MPNm0AlAAAD+p6ZMZLiAHjJ14WxRqaYnb+VBMiNpMBWA09R9FfBQcpplU63bWBAfQJ3cR7twvfJbvGQ8aY6MASYF4JdkjowvZw61gmLjrpYCZuUQvQAA',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — A sunny day with a very elegant witness',
    caption: 'A sunny day with a very elegant witness',
    orientation: 'landscape',
    position: '50% 48%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-004',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-004-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-004-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYAAsAPwFssE6rJiUiMAgBYCAJaACsLwABpZM/h02WTVMtj/92gAD+xeFHCBvbBlKaax9cSfKGSE/02nY8wsHWVTluV58Jw1ApEIwr8Go5jQXfS+LzOiVaFKSQMd10a85PZMX4fBef/t1BUc6bJ++EnS2VZfzq5mbCaxvqx+OgAA==',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — A kiss above the Mediterranean',
    caption: 'A kiss above the Mediterranean',
    orientation: 'landscape',
    position: '50% 50%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-005',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-005-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-005-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoYAAsAPwFurk+rJqQiMAgBYCAJZgC06CIElY/F/SS5874pJeAA/phIv/bA62noVFnta5RR1E1VMSPcUu+YEBCjgphJwOdmi4gVlriBom3/UAc1BL+Qk0/LzBLt5BHuYSdApytTVx/ZjX1z/vRNjgAA',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — Your turn to receive the seaside kiss',
    caption: 'Your turn to receive the seaside kiss',
    orientation: 'landscape',
    position: '50% 50%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-006',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-006-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-006-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoLABgAPwFqrk8rJiQiMAgBYCAJYwCdACIfHFOoSyL+gfK8gAD+tQiLWzxuvoRNhmtOYu4y1vHSUuDP5+M1yeh2TlxqQmx26GDZUeHgoQjHnRK14x3WcVFPjiNtogAA',
    width: 710,
    height: 1536,
    alt: 'Andre and Emily — Sunlight, red sunglasses and you',
    caption: 'Sunlight, red sunglasses and you',
    orientation: 'portrait',
    position: '50% 38%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-007',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-007-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-007-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoYAAsAPwFusFArJqSisAgBYCAJQBTihEBeDK3mJlg98Wbtv63AAP6xTb8ynP3/X2jnGKSvh0JPHrrE0Sx257/ncD/CGc2cz3IfqLWhawDyel0T4wK/ywuwefiHdCQPPy1fP1/NqEjQI/7gAAA=',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — Somewhere between blue skies and pink water',
    caption: 'Somewhere between blue skies and pink water',
    orientation: 'landscape',
    position: '50% 50%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-008',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-008-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-008-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoLABgAPwFsrU8rJiQiMAgBYCAJZgCdMoACOi7ocQ/HPZxVIAD9RNCJezZOZzNa+ozFWOnJ5HFwP3BRhSINFgm176TsSs2HfHPr0MTHX1Eyom98iD/nNAQqEHoSnaVPoHq7OFAA',
    width: 710,
    height: 1536,
    alt: 'Andre and Emily — You, the salt lake and a completely unfair sky',
    caption: 'You, the salt lake and a completely unfair sky',
    orientation: 'portrait',
    position: '50% 44%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-009',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-009-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-009-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoLABgAPwFurk+rJqQiMAgBYCAJZACdMoAA9uGzYaEVtyAA/UUl6oRwH04d2TctYDUTQAHWtbD3FpRYv/edGnsGxIaKPSvr35ccHGVmFx7koR6hHRI2JQbPARnc9UVylBv8NX9QAAA=',
    width: 710,
    height: 1536,
    alt: 'Andre and Emily — The moment you stopped to take it all in',
    caption: 'The moment you stopped to take it all in',
    orientation: 'portrait',
    position: '50% 46%',
    chapter: 'alicante',
  },
  {
    id: 'alicante-010',
    thumbSrc: mediaUrl('photos/trips/alicante/block-01/alicante-010-480.webp'),
    displaySrc: mediaUrl('photos/trips/alicante/block-01/alicante-010-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoSABgAPwFsrlArJiQiqA1RYCAJZwDE2AVxVJOB49fblNr7e7EU2tnAAP61k246h0748Ni1TLHhXS0RXQfQdZZ8fZGqq7DTDHwJuu9uedd3ED48u4CM4QolMcPGJnumo7HqoMlGSms/ZHCdEQVMyHJO5iX4AA==',
    width: 1152,
    height: 1536,
    alt: 'Andre and Emily — The elevator photo that deserved its own chapter',
    caption: 'The elevator photo that deserved its own chapter',
    orientation: 'portrait',
    position: '50% 46%',
    chapter: 'alicante',
  },
]

export default photos
