import { mediaUrl } from '../config/media'
import type { PhotoMemory } from './types'

const photos: PhotoMemory[] = [
  {
    id: 'birthday-001',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-001-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-001-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoMABwAPwFqrk8rJiQiMAgBYCAJYwAAXBv4WzCc2ZZ6c5DvAAD+xUua+cTH6xF07YwRCrbNbrFakjH0mKC5KDgK1Heub8TmskzZxyDsGDzqxN+xiP1A2q9chWrt7c/1qKbA4kO8NwWcNpj37r9vdzjDFkFEO0hWagAAAA==',
    width: 591,
    height: 1280,
    alt: 'Emily — The birthday girl at thirty',
    caption: 'The birthday girl at thirty',
    orientation: 'portrait',
    position: '50% 34%',
    chapter: 'birthday',
  },
  {
    id: 'birthday-002',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-002-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-002-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoMABwAPwFqrU8rJiQiMAgBYCAJQBfJBEHbJtk0GtoF0CQf4e+5kAD+wNDjG2ygGRsgJPs51WN4EfHjcpdUlXChmNmd98QVnvqbAKMIpHtwwtLV5pgSSwLgYk5bixCTWH6GkPIEPHtVIgJDZOxEZYjaAAA=',
    width: 591,
    height: 1280,
    alt: 'Emily — Thirty, but make it cinematic',
    caption: 'Thirty, but make it cinematic',
    orientation: 'portrait',
    position: '50% 50%',
    chapter: 'birthday',
  },
  {
    id: 'birthday-003',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-003-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-003-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoMABwAPwFsrU8rJiQiMAgBYCAJQBhQBD4Oi3haoCgfEP6ExgAA/Nkc76u7B6kHZn0y5tQn03IbX0aZJmI9CEKvjYMf4hST7lzZ43l9r4Lf2OpUsj5jxNMSSQbixsaEVA9GN1yMdqQDfdtrl8K0G7gTDyLdyyXRSMs6QAAA',
    width: 591,
    height: 1280,
    alt: 'Emily — The number three found its star',
    caption: 'The number three found its star',
    orientation: 'portrait',
    position: '50% 50%',
    chapter: 'birthday',
  },
  {
    id: 'birthday-004',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-004-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-004-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAACwBACdASoVABwAPwFwrFCrJqQisBgIAWAgCWcAABzBIo7iHYqiPTZpjNis4cAAAP3SOp2LCs5ByfFsMLkIIz641mgSWBDJFjqkGMRSRDqxhIOOKJ/xnaWO0leFCBTWpgNSz2GAPRs1qQlFXCaAksH5f17rqdGObEWnxR/oYk/aYhmimBl+RJ/bVOlPMMPDqywyhx5jAHEAAA==',
    width: 960,
    height: 1280,
    alt: 'Emily — Strong, playful and completely herself',
    caption: 'Strong, playful and completely herself',
    orientation: 'portrait',
    position: '50% 50%',
    chapter: 'birthday',
  },
  {
    id: 'birthday-005',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-005-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-005-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoPABwAPwF6sFCrKKSisAgBYCAJQBWAAw9lc8r7lCAWe3kMWDGiAAD+y/c/SLW8Zv5Iy5ZM6SoQXtaWHkZ6AEPAXoFV8g6HvUv40Pd4NX0l0VtNqAy/WD++JyEu7+icxrGeJhujRJQQp0fwMxFGRbPrfEmWZFsnDDbn80hKzn7/VmJFRLqATdP+v4mUvXeMgO3hgAAA',
    width: 720,
    height: 1280,
    alt: 'Emily — Those eyes and that quiet smile',
    caption: 'Those eyes and that quiet smile',
    orientation: 'portrait',
    position: '50% 28%',
    chapter: 'birthday',
  },
  {
    id: 'birthday-006',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-006-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-006-1280.webp'),
    blurDataUrl: '',
    width: 960,
    height: 1280,
    alt: 'Emily — Chapter thirty looks beautiful on you',
    caption: 'Chapter thirty looks beautiful on you',
    orientation: 'portrait',
    position: '50% 38%',
    chapter: 'birthday',
  },
  {
    id: 'birthday-007',
    thumbSrc: mediaUrl('photos/birthday/block-01/birthday-007-480.webp'),
    displaySrc: mediaUrl('photos/birthday/block-01/birthday-007-1280.webp'),
    blurDataUrl: '',
    width: 960,
    height: 1280,
    alt: 'Emily — The first page of her next era',
    caption: 'The first page of her next era',
    orientation: 'portrait',
    position: '50% 42%',
    chapter: 'birthday',
  },
]

export default photos
