import { mediaUrl } from '../config/media'
import type { PhotoMemory } from './types'

const photos: PhotoMemory[] = [
  {
    id: 'quiet-001',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-001-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-001-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwBACdASoSABgAPwFqr08rJiSiKA1RYCAJYwAALboE5n1/UAU/dV5CL5iIdxV/74AA/t7IjpHaet4ruCw7/ogYqKYuA3K5lHLiwzLC/13qG5d8AOmAU2heziVqm0pg7i6EI38V0LkZQgAA',
    width: 1152,
    height: 1536,
    alt: 'Andre and Emily — The kind of closeness that makes a normal day feel like home.',
    caption: 'The kind of closeness that makes a normal day feel like home.',
    orientation: 'portrait',
    position: '50% 45%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-002',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-002-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-002-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoNABgAPwFwsE6rJyUiMAgBYCAJQBOgAfBc2VbFl96iAP5xbALIhiOi7d7az7hd93AeDdGmXGYwHrRO+sNLe7WQDtNbYVTy2eeAAA==',
    width: 864,
    height: 1536,
    alt: 'Emily — One of those soft smiles I never get tired of seeing.',
    caption: 'One of those soft smiles I never get tired of seeing.',
    orientation: 'portrait',
    position: '50% 30%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-003',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-003-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-003-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBQCdASoSABgAPwFyrVCrJqQisBgIAWAgCWMAqSdkAZ9I5XAXY55nAp/AepJvynOhLgD+jugE5RS/XRdPow9P2+Tirgy2lJ9fWlQi1a05gptwYH3qwgOE4tZEzA5YwMpIGpwwOrXxdUlr4AA=',
    width: 1152,
    height: 1536,
    alt: 'Andre and Emily — Nothing dramatic. Just us, comfortable and close.',
    caption: 'Nothing dramatic. Just us, comfortable and close.',
    orientation: 'portrait',
    position: '50% 45%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-004',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-004-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-004-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQBACdASoSABgAPv1srU6rJiQiMBgMAWAfiWUAvkgF+PKnYsy0efB5ZP56YVAA2tXalfeuw77ppeKtR5lAJ3cCAT78quUuOSWmT9UXA8QXKkrGcefjBywpL3IrfB8AAAA=',
    width: 1152,
    height: 1536,
    alt: 'Andre and Emily — That smile beside mine makes every photo better.',
    caption: 'That smile beside mine makes every photo better.',
    orientation: 'portrait',
    position: '50% 42%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-005',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-005-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-005-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoYAAsALsGAwGAjqysrCwDASxgE6ZQAOLi4R1bSReJdxAAA/t+xLT/b0XLxUQI3t9dHejfFuhTblwg03ptubJ18+0QCwLAtgAA=',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — A day outside, two smiles, and another memory worth keeping.',
    caption: 'A day outside, two smiles, and another memory worth keeping.',
    orientation: 'landscape',
    position: '50% 48%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-006',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-006-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-006-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQBACdASoLABgAPwFqrk6rJiQiMAgBYCAJQBahBLhggvYe9oxqnMhDYAD+0vk2hWzmW9noikUs3HlDreOefvd0+Nm3plGE2T4AAA==',
    width: 708,
    height: 1536,
    alt: 'Andre and Emily — You in the foreground, me pretending I am the main character.',
    caption: 'You in the foreground, me pretending I am the main character.',
    orientation: 'portrait',
    position: '55% 45%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-007',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-007-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-007-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoYAAsAPwFqrU6rJiQiMAgBYCAJZAAAW89J+M9CXJYAAP6RQz4J5m/xp0Eluel7HOOjyLpcmXXUql2r+wkgHdCAAAA=',
    width: 1536,
    height: 710,
    alt: 'Andre and Emily — One of my favourite views: you beside me and the world behind us.',
    caption: 'One of my favourite views: you beside me and the world behind us.',
    orientation: 'landscape',
    position: '50% 48%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-008',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-008-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-008-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQBACdASoNABgAPwFsrE6rJiQiMAgBYCAJQBOmUABWftl/0c94ukilAAD+ueC6z+Gq2NzD3PefW5qfSIPbVqvp0Or5WtgA',
    width: 864,
    height: 1536,
    alt: 'Emily — The effortless beauty you probably do not even notice in yourself.',
    caption: 'The effortless beauty you probably do not even notice in yourself.',
    orientation: 'portrait',
    position: '50% 28%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-009',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-009-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-009-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoNABgAPwFusFArJqSisAgBYCAJZQCdACFnW9NNXxqHhAeAAP6V051LMoDFl2P5c5hosz9VNJoSi3+C0/PsSYAA',
    width: 864,
    height: 1536,
    alt: "Emily — Confidence, personality and absolutely no need for anyone's permission.",
    caption: "Confidence, personality and absolutely no need for anyone's permission.",
    orientation: 'portrait',
    position: '50% 38%',
    chapter: 'quiet',
  },
  {
    id: 'quiet-010',
    thumbSrc: mediaUrl('photos/quiet-days/block-01/quiet-010-480.webp'),
    displaySrc: mediaUrl('photos/quiet-days/block-01/quiet-010-1280.webp'),
    blurDataUrl: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoSABgAPvFmrE6ppaSiMAwBMB4JYwCsMyGCYnRl9nOxWsF+OeVqpwAA/ocwtYRjMrAlFdWtVAZ31lDd3jf0MmNPfqZZMSeTBovnWBiC59KZ2Za2GXzw0Myplv+ixTgA',
    width: 1152,
    height: 1536,
    alt: 'Andre and Emily — The quiet moments are often the ones I want to keep the longest.',
    caption: 'The quiet moments are often the ones I want to keep the longest.',
    orientation: 'portrait',
    position: '50% 45%',
    chapter: 'quiet',
  },
]

export default photos
